name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws --version

      - name: Deploy to S3
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
          